version: '3.7'

services:
  mongo:
    container_name: mongo-db
    image: mongo
    volumes:
      - ./database/db:/data/db
    ports:
      - 27017:27017

  redis:
    container_name: redis-queue
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - cache:/data
    
  app:
    container_name: node-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - redis

  proxy:
    container_name: node-proxy
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/nginx.conf
      - ./certificates/server.key:/etc/nginx/server_certs/server.key
      - ./certificates/server.crt:/etc/nginx/server_certs/server.crt
    ports:
      - 8080:443

volumes:
  cache:
    driver: local
    