version: '3'

services:
  app:
    container_name: node-app
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - node-network
  
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - 1888:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
    