version: '3'

services:
  app:
    container_name: app-server
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  
  api: 
    container_name: api-rest
    build: 
      context: .
      dockerfile: /api/Dockerfile
    ports:
      - 4000:4000
  
  proxy:
    container_name: proxy-docker
    build: 
      context: .
      dockerfile: /proxy/Dockerfile
    ports:
      - 5000:5000

  redis:
    container_name: redis-queue
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local